# Generated by Django 4.2.2 on 2023-08-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ('-model',), 'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Информационный список о продуктах'},
        ),
        migrations.AlterField(
            model_name='order',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('shop', 'Магазин'), ('buyer', 'Покупатель')], max_length=5, verbose_name='Тип пользователя'),
        ),
    ]
