# Generated by Django 4.2.2 on 2023-08-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_products', '0004_delete_confirmemailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
