# Generated by Django 4.2.2 on 2023-08-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_products', '0005_user_email_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmation_token',
        ),
    ]
